name: event_locator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  email_validator: ^2.1.17
  firebase_auth_web: ^5.7.0
  firebase_storage_web: ^3.6.0
  js: ^0.6.5
  firebase_auth_platform_interface: ^7.0.0
  image_picker: ^0.8.7
  firebase_storage: ^11.0.2
  flutterwave_standard: ^1.0.7
  equatable: ^2.0.3
  qr_flutter: ^4.0.0
  http: ^0.13.6
  firebase_core_web: ^2.24.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_inappwebview: ^6.1.5
  # Remove other overrides unless needed after testing
  # webview_flutter: ^4.13.0
  # webview_flutter_android: ^4.7.0
  # webview_flutter_wkwebview: ^3.22.0
  # webview_flutter_platform_interface: ^2.13.1
  # web: ^1.1.1
  # collection: ^1.19.1
  # meta: ^1.16.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg  # Includes all files in assets/images/
    - assets/images/paid.jpg
    - assets/images/mobile.jpg
    - assets/images/card.jpeg
    - assets/images/mtn.jpg
    - assets/images/airtel.png
