name: event_locator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cloud_firestore: ^5.6.11
  convex_bottom_bar: ^3.2.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  fl_chart: ^0.68.0
  flutter_inappwebview: ^6.1.5
  flutter_map: ^8.1.1
  fluttertoast: ^8.2.12
  flutterwave_standard: ^1.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pretty_qr_code: ^3.4.0
  provider: ^6.1.5
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  web: ^1.1.1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_platform_interface: ^2.13.1
  webview_flutter_wkwebview: ^3.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_inappwebview: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/paid.jpg
    - assets/images/mobile.jpg
    - assets/images/card.jpeg
    - assets/images/mtn.jpg
    - assets/images/airtel.png
    - assets/images/logo.jpg