name: event_locator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  another_flushbar: ^1.10.24
  uuid: ^4.0.0
  pretty_qr_code: ^3.4.0
  qr: ^3.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  fl_chart: ^0.64.0
  

  convex_bottom_bar: ^3.0.0
  
  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  #animation
  flutter_staggered_animations: ^1.1.1

  # HTTP & Networking
  http: ^1.4.0

  # Utilities
  intl: ^0.20.2
  provider: ^6.1.5
  fluttertoast: ^8.2.12
  email_validator: ^3.0.0
  equatable: ^2.0.7
  vm_service: ^15.0.2  # Updated

  # Image Handling
  image_picker: ^1.1.2

  # Payment
  flutterwave_standard: ^1.1.0

  # Webview
  flutter_inappwebview: ^6.1.5

  # Web compatibility
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  firebase_core_platform_interface: ^6.0.0
  firebase_auth_platform_interface: ^7.7.2
  firebase_storage_platform_interface: ^5.2.9
  image_picker_for_web: ^3.0.6
  permission_handler_platform_interface: ^4.3.0
  meta: ^1.17.0
  material_color_utilities: ^0.13.0
  mime: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/paid.jpg
    - assets/images/mobile.jpg
    - assets/images/card.jpeg
    - assets/images/mtn.jpg
    - assets/images/airtel.png
    #- assets/images/logo.jpg
