name: event_locator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  another_flushbar: ^1.10.24
  uuid: ^4.0.0
  pretty_qr_code: ^3.4.0
  qr: ^3.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  fl_chart: ^0.64.0
  flutter_map: ^8.1.1
  carousel_slider: ^4.2.1
  convex_bottom_bar: ^3.0.0

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8

  # Local storage
  shared_preferences: ^2.2.2

  # HTTP & Networking
  http: ^1.4.0

  # Utilities
  intl: ^0.20.2
  provider: ^6.1.5
  fluttertoast: ^8.2.12
  email_validator: ^3.0.0
  equatable: ^2.0.7
  url_launcher: ^6.1.0

  # Map & Location
  google_maps_flutter: ^2.2.5
  geocoding: ^4.0.0
  geolocator: ^14.0.0

  # Image Handling
  image_picker: ^1.1.2
  file_picker: ^8.0.0

  # Payment
  flutterwave_standard: ^1.1.0

  # Webview
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_wkwebview: ^3.22.0
  webview_flutter_platform_interface: ^2.13.1

  # Web compatibility
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_inappwebview: ^6.1.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/paid.jpg
    - assets/images/mobile.jpg
    - assets/images/card.jpeg
    - assets/images/mtn.jpg
    - assets/images/airtel.png
    - assets/images/logo.jpg
    - assets/images/blue.jpeg
    - assets/images/blue2.jpeg
    - assets/images/orange.jpeg
    - assets/images/logoo.jpeg
    - assets/images/logo.jpeg
