name: event_locator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.0
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  email_validator: ^2.1.17
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7
  firebase_auth_web: ^5.4.0
  firebase_storage_web: ^3.2.0
  firebase_core_web: ^2.9.0
  js: ^0.6.7
  flutterwave_standard: ^1.0.7
  equatable: ^2.0.3
  qr_flutter: ^4.0.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  flutter_inappwebview: ^5.7.2+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/paid.jpg
    - assets/images/mobile.jpg
    - assets/images/card.jpeg
    - assets/images/mtn.jpg
    - assets/images/airtel.png
