// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtNXk-PGZZd6yej4fdttTeZwyPqF5iZ0c',
    appId: '1:705148128969:web:650226b888bcd3e5d18718',
    messagingSenderId: '705148128969',
    projectId: 'papers-1ddd0',
    authDomain: 'papers-1ddd0.firebaseapp.com',
    databaseURL: 'https://papers-1ddd0-default-rtdb.firebaseio.com',
    storageBucket: 'papers-1ddd0.appspot.com',
    measurementId: 'G-7PHHD7MPXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WKEIncfED-1yqFQjUXRkpgVDO1lCoeU',
    appId: '1:705148128969:android:f86f3e71008bda49d18718',
    messagingSenderId: '705148128969',
    projectId: 'papers-1ddd0',
    databaseURL: 'https://papers-1ddd0-default-rtdb.firebaseio.com',
    storageBucket: 'papers-1ddd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzR5bSNpdFnF_toYkOuSJpc5j1yrvU0c',
    appId: '1:705148128969:ios:871b4e036e3f20d5d18718',
    messagingSenderId: '705148128969',
    projectId: 'papers-1ddd0',
    databaseURL: 'https://papers-1ddd0-default-rtdb.firebaseio.com',
    storageBucket: 'papers-1ddd0.appspot.com',
    iosClientId: '705148128969-pkl8fqphtirtsm2je3ursafh0hmsnua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventLocatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtNXk-PGZZd6yej4fdttTeZwyPqF5iZ0c',
    appId: '1:705148128969:web:cc8cf3c672f8ed63d18718',
    messagingSenderId: '705148128969',
    projectId: 'papers-1ddd0',
    authDomain: 'papers-1ddd0.firebaseapp.com',
    databaseURL: 'https://papers-1ddd0-default-rtdb.firebaseio.com',
    storageBucket: 'papers-1ddd0.appspot.com',
    measurementId: 'G-4BYV9XZ8YP',
  );

}