// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYN5O3x4VfH5w-AP0rx79JfmUyxtOEpc',
    appId: '1:705100681997:web:16da1e5ce845c5e0ae5644',
    messagingSenderId: '705100681997',
    projectId: 'kennedy-cf610',
    authDomain: 'kennedy-cf610.firebaseapp.com',
    storageBucket: 'kennedy-cf610.firebasestorage.app',
    measurementId: 'G-Y6ZR0C7FTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb--C8pmBLZvbZR544dvIW4v_IHVJquIk',
    appId: '1:705100681997:android:871d44fc69253de2ae5644',
    messagingSenderId: '705100681997',
    projectId: 'kennedy-cf610',
    storageBucket: 'kennedy-cf610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwz-AQLezWQBsuyRyCMvzxMZMKcigN80',
    appId: '1:705100681997:ios:54f91d69c355352aae5644',
    messagingSenderId: '705100681997',
    projectId: 'kennedy-cf610',
    storageBucket: 'kennedy-cf610.firebasestorage.app',
    iosBundleId: 'com.example.eventLocatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYN5O3x4VfH5w-AP0rx79JfmUyxtOEpc',
    appId: '1:705100681997:web:33eeca2451de745eae5644',
    messagingSenderId: '705100681997',
    projectId: 'kennedy-cf610',
    authDomain: 'kennedy-cf610.firebaseapp.com',
    storageBucket: 'kennedy-cf610.firebasestorage.app',
    measurementId: 'G-D65EEJHGKD',
  );
}
